employee_management_project/auth_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             template_name='auth_app/login.html',
         ),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(),
         name='logout'),
]

employee_management_project/employee_management_project/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_swagger.views import get_swagger_view
from management_app.api.urls import router

urlpatterns = [
    path('', include('management_app.urls', namespace='management_app')),
    path('', include('auth_app.urls')),
    # Django authentication
    path('api/', include(router.urls)),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('docs/', get_swagger_view(title='Management API'), name='docs'),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    # DRF API authentication(same session with Django)
    path('api-auth/', include('rest_framework.urls')),
]

employee_management_project/management_app/api/urls.py
from rest_framework import routers
from management_app.api import views


router = routers.DefaultRouter()

router.register(r'companies', views.CompanyViewSet)
router.register(r'managers', views.ManagerViewSet)
router.register(r'employees', views.EmployeeViewSet)
router.register(r'jobs', views.JobViewSet)
router.register(r'workplaces', views.WorkPlaceViewSet)
router.register(r'worktimes', views.WorkTimeViewSet)
router.register(r'statistics', views.StatisticsViewSet)

employee_management_project/management_app/urls.py
from django.urls import path
from . import views


app_name = 'management'

urlpatterns = [
    path('',
         views.CompaniesListView.as_view(),
         name='companies_list'),
    path('company/<int:pk>/details/',
         views.CompanyDetailsView.as_view(),
         name='company_details'),
    path('company/<int:company_id>/managers/',
         views.CompanyManagersListView.as_view(),
         name='company_managers_list'),
    path('company/<int:company_id>/job-create/',
         views.CreateJobView.as_view(),
         name='job_create'),
    path('employees-list/',
         views.EmployeesListView.as_view(),
         name='employees_list'),
    path('employee/<int:pk>/details/',
         views.EmployeeDetailsView.as_view(),
         name='employee_details'),
    path('workplace/<int:pk>/hire/',
         views.HireEmployeeView.as_view(),
         name='workplace_hire'),
    path('workplace/<int:workplace_id>/worktime-create/',
         views.CreateWorkTimeView.as_view(),
         name='worktime_create'),
]

employee_management_project/management_app/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


# Constants for status field
NEW = 'N'
APPROVED = 'A'
CANCELLED = 'C'
FINISHED = 'F'


class Company(models.Model):
    """Company model."""
    name = models.CharField(max_length=100, unique=True)
    weekly_hours_limit = models.IntegerField()

    def __str__(self):
        return f'"{self.name}"(id:{self.id}) the Company'

    class Meta:
        verbose_name_plural = 'Companies'


class Manager(models.Model):
    """Manager model."""
    company = models.ForeignKey(
        Company,
        related_name='managers',
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)

    def __str__(self):
        return (f'{self.name}(id:{self.id}) '
                f'the Manager at {self.company}')


class Employee(models.Model):
    """Employee model."""
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}(id:{self.id}) the Employee'


class Job(models.Model):
    """Job model."""
    company = models.ForeignKey(
        Company,
        related_name='jobs',
        on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}(id:{self.id}) the Job at {self.company}'

    class Meta:
        unique_together = ('company', 'name')


class WorkPlace(models.Model):
    """Work place model."""
    STATUS = [
        (NEW, 'New'),
        (APPROVED, 'Approved'),
        (CANCELLED, 'Cancelled'),
        (FINISHED, 'Finished'),
    ]

    job = models.ForeignKey(
        Job,
        related_name='workplaces',
        on_delete=models.CASCADE)
    employee = models.ForeignKey(
        Employee,
        related_name='workplaces',
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    status = models.CharField(
        max_length=1,
        choices=STATUS,
        default=NEW,
    )

    def __str__(self):
        return f'Work place(id:{self.id}) of {self.job}'

    class Meta:
        unique_together = ('job', 'employee')
        ordering = ('-employee',)


class WorkTime(models.Model):
    """Worktime model."""
    workplace = models.ForeignKey(
        WorkPlace,
        on_delete=models.CASCADE,
        related_name='worktimes',
    )
    date = models.DateField()
    hours_worked = models.IntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(12),
        ]
    )

    def __str__(self):
        return f'WorkTime({self.id}) of {self.workplace}({self.workplace.id})'

    class Meta:
        unique_together = ('workplace', 'date')
        ordering = ('-date',)


class Statistics(models.Model):
    """Statistics model.
    Object: the sum of the working hours 
    of individual employees at 7-day intervals
    and timestamp.
    """
    workplace = models.ForeignKey(
        WorkPlace,
        on_delete=models.CASCADE,
    )
    hours_total = models.IntegerField()
    timestamp = models.DateTimeField(auto_now_add=True)

employee_management_project/management_app/forms.py
from django import forms
from django.utils import timezone

from .models import WorkTime


class WorkTimeForm(forms.ModelForm):
    """WorkTime form."""
    class Meta:
        model = WorkTime
        fields = ('workplace', 'date', 'hours_worked')

    def clean_date(self):
        data = self.cleaned_data['date']
        if data != timezone.localdate():
            raise forms.ValidationError('Date must be today')
        return data

employee_management_project/management_app/api/views.py
from rest_framework import viewsets
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAuthenticated
from rest_framework.decorators import action
from rest_framework.response import Response

from management_app.models import (Company, Manager, Employee, Job,
                                   WorkPlace, WorkTime, Statistics,)
from .serializers import (CompanySerializer, ManagerSerializer, EmployeeSerializer,
                          JobSerializer, WorkPlaceSerializer, WorkTimeSerializer,
                          StatisticsSerializer, StatisticsUpdateSerializer)


class CompanyViewSet(viewsets.ReadOnlyModelViewSet):
    permission_classes = (IsAuthenticated,)

    queryset = Company.objects.all()
    serializer_class = CompanySerializer


class ManagerViewSet(viewsets.ModelViewSet):
    queryset = Manager.objects.all()
    serializer_class = ManagerSerializer


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer


class JobViewSet(viewsets.ModelViewSet):
    queryset = Job.objects.all()
    serializer_class = JobSerializer


class WorkPlaceViewSet(viewsets.ModelViewSet):
    queryset = WorkPlace.objects.all()
    serializer_class = WorkPlaceSerializer


class WorkTimeViewSet(viewsets.ModelViewSet):
    queryset = WorkTime.objects.all()
    serializer_class = WorkTimeSerializer


class StatisticsViewSet(viewsets.ModelViewSet):
    queryset = Statistics.objects.all()
    serializer_class = StatisticsSerializer

    def get_serializer_class(self):
        serializer_class = self.serializer_class

        if self.request.method in ('PUT', 'PATCH'):
            serializer_class = StatisticsUpdateSerializer

        return serializer_class

    @action(detail=False)
    def hours_descend(self, request):
        statistics_hours_descend = Statistics.objects.all().order_by('-hours_total')

        page = self.paginate_queryset(statistics_hours_descend)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(statistics_hours_descend, many=True)
        return Response(serializer.data)

employee_management_project/management_app/views.py
import logging

from django.shortcuts import get_object_or_404
from django.views.generic import (ListView, DetailView,
                                  CreateView, UpdateView, FormView)
from django.db.models import Q

from .models import (Company, Manager, Employee, Job,
                     WorkPlace, WorkTime)
from .models import APPROVED, FINISHED
from .forms import WorkTimeForm


sentry_logger = logging.getLogger('sentry_logger')


class CompaniesListView(ListView):
    """Companies list View."""
    model = Company
    template_name = 'management_app/companies_list.html'
    context_object_name = 'companies'


class CompanyDetailsView(DetailView):
    """Companies details View."""
    model = Company
    template_name = 'management_app/company_details.html'


class CompanyManagersListView(ListView):
    """Company managers View."""
    model = Manager
    template_name = 'management_app/managers_list.html'
    context_object_name = 'managers'

    def get_queryset(self):
        company = get_object_or_404(Company, id=self.kwargs.get('company_id'))
        return Manager.objects.filter(company=company)


class CreateJobView(CreateView):
    """Create job View."""
    model = Job
    fields = ('company', 'name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next', '/')
        return context

    def get_initial(self):
        company = get_object_or_404(Company, id=self.kwargs.get('company_id'))
        return {'company': company}

    def get_success_url(self):
        return self.request.GET.get('next', '/')

    def form_valid(self, form):
        self.object = form.save()

        posted_data = self.request.POST
        sentry_logger.debug(
            'Job data',
            extra={
                'company_id': posted_data['company'],
                'job_name': posted_data['name']
            }
        )
        sentry_logger.info('Created Job')

        return super().form_valid(form)


class EmployeesListView(ListView):
    """Employees list View."""
    model = Employee
    template_name = 'management_app/employees_list.html'
    context_object_name = 'employees'


class EmployeeDetailsView(DetailView):
    """Employee details View."""
    model = Employee
    template_name = 'management_app/employee_details.html'

from django.http import HttpResponse
from django.db import IntegrityError
class HireEmployeeView(UpdateView):
    """Hire employee View."""
    model = WorkPlace
    fields = ('employee',)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next', '/')
        return context

    def get_success_url(self):
        return self.request.GET.get('next', '/')

    def form_valid(self, form):
        try:
            self.object = form.save(commit=False)
            # set status of 'approved' when the employee is hired
            self.object.status = APPROVED
            self.object.save()

            # set status of 'finished' for previous workplaces of the employee
            employee = self.object.employee
            prev_unfinished_workplaces = employee.workplaces.exclude(
                Q(id=self.object.id) | Q(status=FINISHED)
            )
            for workplace in prev_unfinished_workplaces:
                workplace.status = FINISHED
                workplace.save()

            posted_data = self.request.POST
            if posted_data['employee']:
                sentry_logger.debug(
                    'Employee data',
                    extra={
                        'employee_id': posted_data['employee'],
                    }
                )
                sentry_logger.info('Hired employee')

            return super().form_valid(form)

        except IntegrityError as e:
            form.add_error('employee', 'This employee has already been hired for this job.')

            return self.form_invalid(form)


class CreateWorkTimeView(FormView):
    """Create worktime View."""
    form_class = WorkTimeForm
    template_name = 'management_app/worktime_form.html'

    def get_initial(self):
        workplace = get_object_or_404(
            WorkPlace, id=self.kwargs.get('workplace_id'))
        return {'workplace': workplace}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['next'] = self.request.GET.get('next', '/')
        return context

    def get_success_url(self):
        return self.request.GET.get('next', '/')

    def form_valid(self, form):
        self.object = form.save()

        posted_data = self.request.POST
        sentry_logger.debug(
            'Worktime data',
            extra={
                'workplace_id': posted_data['workplace'],
                'date': posted_data['date'],
                'hours_worked': posted_data['hours_worked'],
            }
        )
        sentry_logger.info('Created worktime')

        return super().form_valid(form)

employee_management_project/management_app/templates/management_app/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block css_link %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'index' %}">Management</a>
    </nav>


    {% block content %}{% endblock %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

employee_management_project/management_app/templates/management_app/companies_list.html
{% extends 'layout.html' %}
{% block title %}Companies list{% endblock %}


{% block content %}
<h1>Companies list:</h1>
<ul class='companies-list'>
    {% for company in companies %}
    <li><a href="{% url 'management:company_details' company.id %}">{{ company.name }}</a></li>
    {% empty %}
    <li>There are no companies</li>
    {% endfor %}
</ul>

<script>
    var companiesListSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/');

    companiesListSocket.onmessage = function (e) {
        var data = JSON.parse(e.data);
        var reload_page = data['reload_page'];

        if (reload_page) {
            location.reload();
        }
    };

    companiesListSocket.onclose = function (e) {
        console.error('Chat socket closed unexpectedly');
    };
</script>

{% endblock %}

employee_management_project/management_app/templates/management_app/company_details.html
{% extends 'layout.html' %}
{% block title %}Companies list{% endblock %}

{% load static %}
{% block css_link %}
<link rel="stylesheet" href="{% static 'management_app/css/details.css' %}">
{% endblock %}

{% block content %}

<div>
    <hr>
    <h1>Company name: {{ company.name }}</h1>

    <hr>
    <a href="{% url 'management:company_managers_list' company.id %}">Managers list</a>

    <hr>
    <p>Jobs:</p>
    {% if not company.jobs.all %}
    <p class='not-found'>There are no jobs in the company</p>
    {% endif %}

    <div class='work-list-container'>

        <div class="work-list-item">
            <a href="{% url 'management:job_create' company.id %}?next={{ request.path }}">Create new job</a>
        </div>

        {% for job in company.jobs.all %}
        <div class='work-list-item'>
            <p>{{ job.name }}</p>
            {% if job.workplaces.all %}
            <ol>
                {% for workplace in job.workplaces.all %}
                <li>
                    {% if workplace.employee %}
                    <span>
                        {{ workplace.employee.name }}
                        ({{ workplace.get_status_display }})
                    </span>
                    {% else %}
                    <a href="{% url 'management:workplace_hire' pk=workplace.id %}?next={{ request.path }}" class='vacant-place'>
                        Vacant place
                    </a>
                    {% endif %}
                </li>
                {% endfor %}
            </ol>
            {% else %}
            <p class='not-found'>There are no work places at this company job</p>
            {% endif %}
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

employee_management_project/management_app/templates/management_app/employee_details.html
{% extends 'layout.html' %}
{% block title %}Employee details{% endblock %}

{% load static %}
{% block css_link %}
<link rel="stylesheet" href="{% static 'management_app/css/details.css' %}">
{% endblock %}

{% block content %}

<div>

    <hr>
    <h1> Employee name: {{ employee.name }}</h1>
    <hr>
    <p>Workplaces:</p>
    <div class="work-list-container">

        {% for workplace in employee.workplaces.all %}
        <div class="work-list-item">
            
            <p>{{ workplace.job.name }} in {{ workplace.job.company.name }}</p>
            {% if workplace.get_status_display == 'Approved' %}
            <a href="{% url 'management:worktime_create' workplace.id %}?next={{ request.path }}">Create worktime</a>
            {% else %}
            <p class='not-found'>Finished</p>
            {% endif %}

            {% for wtime in workplace.worktimes.all|slice:':7' %}
            <div class="border border-info mb-2">
                <p>Date: {{ wtime.date }}</p>
                <p>Hours worked: {{ wtime.hours_worked }}</p>
            </div>
            {% endfor %}
        </div>
        {% empty %}
        <p class='not-found'>There are no workplaces</p>
        {% endfor %}

    </div>

</div>

{% endblock %}

employee_management_project/management_app/templates/management_app/employees_list.html
{% extends 'layout.html' %}
{% block title %}Employees list{% endblock %}

{% load static %}
{% block css_link %}

{% endblock %}

{% block content %}
<h1>Employees list:</h1>
<ul>
    {% for employee in employees %}
    <li>
        <a href="{% url 'management:employee_details' employee.id %}">
            {{ employee.name }}
        </a>
    </li>
    {% empty %}
    <li>There are no employees</li>
    {% endfor %}
</ul>
{% endblock %}

employee_management_project/management_app/templates/management_app/index.html
{% extends 'management_app/layout.html' %}
{% block title %}Companies list{% endblock %}

{% load static %}
{% block css_link %}
<link rel="stylesheet" href="{% static 'management_app/css/index.css' %}">
{% endblock %}

{% block content %}
    <h1>Companies list:</h1>
    <ul class='companies-list'>
    {% for company in companies %}
        <li><a href="{% url 'details' company.id %}">{{ company.name }}</a></li>
    {% empty %}
        <li>There are no companies</li>
    {% endfor %}
    </ol>
{% endblock %}

employee_management_project/management_app/templates/management_app/job_form.html
{% extends 'layout.html' %}
{% load i18n %}
{% block title %}{% trans 'Create job' %}{% endblock %}

{% load static %}
{% block css_link %}

{% endblock %}

{% block content %}
<div class='form'>
    <h1>{% trans 'Create job' %}</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value={% trans "Save" %}>
        <a href="{{ next }}">Cancel</a>
    </form>
</div>
{% endblock %}

employee_management_project/management_app/templates/management_app/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Datetimepicker -->
    <link rel="stylesheet" href="{% static 'management_app/dtpicker/jquery.datetimepicker.min.css' %}">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/2c036519fc.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'management_app/css/layout.css' %}">
    {% block css_link %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <!-- Datetimepicker -->
    <script src="{% static 'management_app/dtpicker/jquery.datetimepicker.full.min.js' %}"></script>
    
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-primary">
            <a class="navbar-brand" href="#">Management</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'companies_list' %}">Companies list</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'employees_list' %}">Employees list</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <main>
        <div class="container">
            <div class="row mt-4 justify-content-center">
                <div class="col-6">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </main>

</body>

</html>

employee_management_project/management_app/templates/management_app/managers_list.html
{% extends 'layout.html' %}
{% load i18n %}
{% block title %}{% trans 'Managers list' %}{% endblock %}

{% block content %}
<h1>{% trans 'Managers list' %}:</h1>
<ul>
    {% for manager in managers %}
    <li>
        {{ manager.name }}
    </li>
    {% empty %}
    <li>
        <span class='not-found'>{% trans 'There are no managers' %}</span>
    </li>
    {% endfor %}
</ul>
{% endblock %}

employee_management_project/management_app/templates/management_app/workplace_form.html
{% extends 'layout.html' %}
{% load i18n %}
{% block title %}{% trans 'Hire employee' %}{% endblock %}

{% load static %}
{% block css_link %}

{% endblock %}

{% block content %}
<div class="form">
    <h1>{% trans 'Hire employee' %}</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value={% trans "Save" %}>
        <a href="{{ next }}">{% trans 'Cancel' %}</a>
    </form>
</div>
{% endblock %}

employee_management_project/management_app/templates/management_app/worktime_form.html
{% extends 'layout.html' %}
{% load i18n %}
{% block title %}{% trans 'Worktime create' %}{% endblock %}

{% load static %}
{% block css_link %}

{% endblock %}

{% block content %}
<div class='form'>
    <h1>{% trans 'Create worktime for workplace' %}</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value={% trans "Save" %}>
        <a href="{{ next }}">{% trans 'Cancel' %}</a>
    </form>
</div>

<script>
    $('#id_date').datetimepicker({
        timepicker: false,
        datepicker: true,
        format: 'm/d/Y',
        onShow: function (ct) {
            this.setOptions({
                minDate: Date(),
                maxDate: Date()
            })
        }
    })
</script>
{% endblock %}