employee_management_project/auth_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(
             template_name='auth_app/login.html',
         ),
         name='login'),
    path('logout/',
         auth_views.LogoutView.as_view(),
         name='logout'),
]

employee_management_project/employee_management_project/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_swagger.views import get_swagger_view
from management_app.api.urls import router

urlpatterns = [
    path('', include('management_app.urls', namespace='management_app')),
    path('', include('auth_app.urls')),
    # Django authentication
    path('api/', include(router.urls)),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('docs/', get_swagger_view(title='Management API'), name='docs'),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    # DRF API authentication(same session with Django)
    path('api-auth/', include('rest_framework.urls')),
]

employee_management_project/management_app/urls.py
from django.urls import path
from . import views


app_name = 'management'

urlpatterns = [
    path('',
         views.CompaniesListView.as_view(),
         name='companies_list'),
    path('company/<int:pk>/details/',
         views.CompanyDetailsView.as_view(),
         name='company_details'),
    path('company/<int:company_id>/managers/',
         views.CompanyManagersListView.as_view(),
         name='company_managers_list'),
    path('company/<int:company_id>/job-create/',
         views.CreateJobView.as_view(),
         name='job_create'),
    path('employees-list/',
         views.EmployeesListView.as_view(),
         name='employees_list'),
    path('employee/<int:pk>/details/',
         views.EmployeeDetailsView.as_view(),
         name='employee_details'),
    path('workplace/<int:pk>/hire/',
         views.HireEmployeeView.as_view(),
         name='workplace_hire'),
    path('workplace/<int:workplace_id>/worktime-create/',
         views.CreateWorkTimeView.as_view(),
         name='worktime_create'),
]

employee_management_project/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Datetimepicker -->
    <link rel="stylesheet" href="{% static 'dtpicker/jquery.datetimepicker.min.css' %}">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/2c036519fc.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    {% block css_link %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <!-- Datetimepicker -->
    <script src="{% static 'dtpicker/jquery.datetimepicker.full.min.js' %}"></script>

    <header>
        <nav class="navbar navbar-expand navbar-dark bg-primary">
            <a class="navbar-brand" href="#">Management</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'management:companies_list' %}">Companies list</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'management:employees_list' %}">Employees list</a>
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">
                            {{ user.username }} (Log out)
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log in</a>
                    </li>
                    {% endif %}
                </ul>

            </div>
        </nav>
    </header>

    <main>
        <div class="container">
            <div class="row mt-4 justify-content-center">
                <div class="col-6">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </main>

</body>

</html>